# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    acme_api.event.jwt_created_listener:
        class: App\Events\JWTAddData
        arguments: [ '@App\Repository\UsersRepository' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: addDataToJWT }


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Services\ApiCaller:
        arguments:
            $apiKey: '%env(NEWS_API_KEY)%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
